- .goreleaser.yml
- scripts/completions.sh
The shell completion will be now part of the release archives, and we will use the `HomeBrew` `completion` feature to automatically install the completion for the supported types of shell.
> Install shell completions directly

- .github/workflows/releases.yml
- Makefile
- pkg/cmdutil/jsonpath_flags.go
Automatically generate and push the generated `.yml` files to the documentation repository on release.
> Automatically publish the docs `.yml` files on release

- pkg/cmd/objects/import/import.go
- pkg/cmd/objects/import/import_test.go
- pkg/cmd/rules/import/import.go
- pkg/cmd/rules/import/import_test.go
- pkg/cmd/synonyms/import/import.go
- pkg/cmd/synonyms/import/import_test.go
Small improvements for the commands expecting a `json-nd` input (`synonyms`, `objects` and `rules` commands):
- Adding a link to the json-nd specs in the help message:
> The file must contains one single JSON object per line (newline delimited JSON objects - ndjson format: https://ndjson.org/).
- Better error message when parsing issues are happening, with the line number:
> failed to parse JSON object on line 0: invalid character ',' after object key
> [DEX-90] Improve help and error messages for json-nd imports

- pkg/cmd/objects/delete/delete.go
- pkg/cmd/objects/delete/delete_test.go
- pkg/cmd/rules/delete/delete.go
- pkg/cmd/rules/delete/delete_test.go
- pkg/cmd/synonyms/delete/delete.go
- pkg/cmd/synonyms/delete/delete_test.go
Add the `objects delete`, `synonyms delete` and `rules delete` commands.
Example usage:
```
$ algolia objects delete TEST_PRODUCTS_1 --object-ids 1
```
> [DEX-107] Add objects,synonyms,rules delete commands

- pkg/cmd/profile/remove/remove.go
- pkg/cmd/profile/remove/remove_test.go
Bug fix for the removal of a profile, when no existing default profile are set. The `opts.config.Default()` would be then `nil`, and accessing the `Name` would fire a nil pointer error.
We are fixing this by checking / storing the default profile early, and by storing the name in the command options.
> fix(config) Remove profile without default

- pkg/cmd/apikeys/create/create.go
This PR corrects the docs for the `--description` option.
> fix: typo lead to wrong fact

- pkg/cmd/open/open.go
This PR fixes the link to the CLI Docs, so that `algolia open cli-docs` works properly.
> fix: broken link to CLI Docs

- pkg/config/config.go
Fixing the behaviour of the `SetDefaultProfile` when dealing with a non-existent (at least in memory) config file.
Fix #68
> fix(profile): Reload config before setting the default

- Makefile
- pkg/cmd/objects/browse/browse.go
- pkg/cmdutil/spec_flags.go
- pkg/gen/gen_flags.go
**⚠️ Related to [this PR](https://github.com/algolia/api-clients-automation/pull/1043): we should wait for this fix and trigger a generation before merging this PR** 
- Generating flags for `browse` commands from `BrowseParamsObject` instead of `SearchParamsObject`
> [DEX-228] fix: browse flags gen

- objects-update.json
- pkg/cmd/objects/objects.go
- pkg/cmd/objects/update/object.go
- pkg/cmd/objects/update/object_test.go
- pkg/cmd/objects/update/update.go
- pkg/cmd/objects/update/update_test.go
The objects update command is available, allowing the users to partially update the objects in their indices.
- Can't make [`autoGenerateObjectIDIfNotExist`](https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/#method-param-autogenerateobjectidifnotexist) work. Got this error: "could not generate intermediate batch: missing `objectID` field in object"
> [DEX-334] feat: algolia objects update

- api/insights/client.go
- api/insights/responses.go
- api/insights/types.go
- api/insights/utils.go
- pkg/cmd/events/events.go
- pkg/cmd/events/tail/tail.go
- pkg/cmd/root/root.go
This PR add a new `events tail` command.
> [DEX-332] Add events tail command

- .github/workflows/releases.yml
- .goreleaser.yml
- pkg/iostreams/console.go
- pkg/iostreams/tty_size_windows.go
This PR enables our goreleaser to create a windows build (`.exe`) and pushes it as a package to Chocolatey.
Chocolatey doesn't require a signed executable making it possible to build a `nupkg` and installing it without needing a signed exe.
Chocolatey has a [heavy moderation process](https://docs.chocolatey.org/en-us/community-repository/moderation/), therefore it may take quite some time before the package gets approved (2-3 days) per my experience.
The following PR should pass the automated review if all the links added to the chocolatey releaser are not broken links (should therefore be double checked)
> [DEX-386] Add windows support and release to chocolatey

- go.mod
- go.sum
Update the algoliasearch-client-go deps to get the latest fix
> chore(deps): bump algolia/algoliasearch-client-go/v3 from v3.26.4 to v3.27.0

- pkg/cmd/profile/remove/remove_test.go
Fix flaky test:
```
remove_test.go:149: 
Error Trace:	/home/runner/work/cli/cli/pkg/cmd/profile/remove/remove_test.go:149
Error:      	Not equal: 
expected: "✓ 'foo' removed successfully.\n"
actual  : "✓ 'foo' removed successfully. Set a new default profile with 'algolia profile setdefault'.\n"
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-✓ 'foo' removed successfully.
+✓ 'foo' removed successfully. Set a new default profile with 'algolia profile setdefault'.
Test:       	Test_runRemoveCmd/existing_profile_(non-default)
```
This test is flaky due to the go maps which doesn't have a predictable order and the function `test.NewConfigStubWithProfiles` relies on the order to define the profile used. This PR leverages a slice to have a predictable ordering
> test: remove flaky test due to map ordering randomness

- pkg/cmd/dictionary/entries/browse/browse.go
- pkg/cmd/dictionary/entries/clear/clear.go
- pkg/cmd/dictionary/entries/import/import.go
- pkg/cmd/events/tail/tail.go
- pkg/cmd/objects/browse/browse.go
- pkg/cmd/objects/delete/delete.go
- pkg/cmd/objects/operations/operations.go
- pkg/cmd/objects/update/update.go
- pkg/cmd/profile/add/add.go
- pkg/cmd/profile/remove/remove.go
- pkg/cmd/profile/setdefault/setdefault.go
- pkg/cmd/rules/browse/browse.go
- pkg/cmd/synonyms/browse/browse.go
Check error when writing on the output: I dumped a large index on a disk full and the cli didn't return an error.
I only added error handling for the calls without check on `IO.IsStdoutTTY` or using `IO.ErrOut`.
> fix(cli): check error when writing on the output

- internal/docs/yaml.go
- pkg/cmd/dictionary/dictionary.go
- pkg/cmd/dictionary/entries/browse/browse.go
- pkg/cmd/dictionary/entries/browse/browse_test.go
- pkg/cmd/dictionary/entries/clear/clear.go
- pkg/cmd/dictionary/entries/clear/clear_test.go
- pkg/cmd/dictionary/entries/delete/delete.go
- pkg/cmd/dictionary/entries/delete/delete_test.go
- pkg/cmd/dictionary/entries/entries.go
- pkg/cmd/dictionary/settings/settings.go
- pkg/cmd/dictionary/shared/constants.go
This PR adds rendering the sub-subcommands from `algolia index config` and `algolia dictionary {settings,entries}` correctly. 
This PR also corrects the numbering of the commands in the reference, so that they appear alphabetically, like in the terminal. 
The actual rendering of the YAML will be done in the documentation repo. 
[DEX-810]
[DEX-810]: https://algolia.atlassian.net/browse/DEX-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: documentation rendering issues

- pkg/cmd/indices/delete/delete.go
- pkg/cmd/indices/delete/delete_test.go
This PR adds a new boolean option to the `algolia indices delete` command: `--includeReplicas`. 
If it's true, the command will look for any replicas of an index and deletes them with the primary index. No more dangling indices because of replicas. 
[DEX-784]
[DEX-784]: https://algolia.atlassian.net/browse/DEX-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(cli): also delete replica indices

- pkg/gen/gen_flags.go
The newly added backticks in the Open API specs was crashing the auto-generated flags generation.
> fix(gen) Escape backticks during the flags generation

- .github/workflows/go.yml
- .github/workflows/releases.yml
- Makefile
- cmd/docs/main.go
- internal/docs/docs.go
- internal/docs/mdx.go
- internal/docs/mdx.tpl
- internal/docs/yaml.go
- pkg/cmd/indices/list/list.go
- pkg/cmd/search/search.go
This PR create a command to generate a `new-world-docs` PR that'll update the `.mdx` files for the CLI documentation.
```sh
go run ./cmd/docs --app_data-path docs/app_data/cli/commands --target new
```
It will output the files in at `docs/app_data/cli/commands`
Summary of our discussion with @clemfromspace:
- We'll add annotation (`runInWebCli`) to commands with `web CLI` enabled in `new-world-docs`
- Because there's differences between CLI examples and the ones run with the `web CLI`, we'll standardize all examples with the `new-world-docs`/`webCLI` (in a future PR)
- Examples with output or pipe symbols will automatically be non-runnable
[DEX-1021]: https://algolia.atlassian.net/browse/DEX-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(automation): new world doc pr creation

- internal/docs/mdx.tpl
- pkg/cmd/apikeys/create/create.go
- pkg/cmd/crawler/crawl/crawl.go
- pkg/cmd/crawler/test/test.go
- pkg/cmd/indices/clear/clear.go
- pkg/cmd/indices/config/export/export.go
- pkg/cmd/indices/config/import/import.go
- pkg/cmd/indices/copy/copy.go
- pkg/cmd/indices/delete/delete.go
- pkg/cmd/indices/move/move.go
- pkg/cmd/objects/browse/browse.go
- pkg/cmd/objects/delete/delete.go
- pkg/cmd/objects/import/import.go
- pkg/cmd/objects/update/update.go
- pkg/cmd/root/root.go
- pkg/cmd/rules/browse/browse.go
- pkg/cmd/rules/delete/delete.go
- pkg/cmd/rules/import/import.go
- pkg/cmd/search/search.go
- pkg/cmd/settings/get/list.go
- pkg/cmd/settings/import/import.go
- pkg/cmd/settings/set/set.go
- pkg/cmd/synonyms/browse/browse.go
- pkg/cmd/synonyms/delete/delete.go
- pkg/cmd/synonyms/import/import.go
- pkg/cmd/synonyms/save/save.go
- update all the examples in the CLI to match `new-world-docs` indexes and context
- enable `runInWebCLI` option for the commands and examples runnable by the web CLI in the `new-world-docs`
- fix `.mdx` template
> feat(examples): matching new world docs indexes and dataset [DEX-1048]

- pkg/cmd/objects/update/update.go
Correct the `--continue-on-error` flag mentioned in the usage examples of the `algolia objects update` command.
> fix: continue-on-error

- api/specs/search.yml
- internal/analyze/analyze.go
- internal/analyze/analyze_test.go
- pkg/cmd/indices/analyze/analyze.go
- pkg/cmd/indices/index.go
This PR contains the CLI implementation of the `index analyzer` tool from https://github.com/algolia/tools.
> This command displays records statistics - frequency of the attributes and their types - for the specified index.
> This can be useful to help you identify individual records (or attributes) within an index that do not conform to the rest of the dataset (e.g. numeric attributes that have null values).
```
$ algolia -p media indices analyze prod_MEDIA
KEY                                 COUNT  %        TYPES                                            USED IN SETTINGS
backdrop_path                       1000   100.00%  string: 100.00%                                  []
bayesian_avg                        1000   100.00%  numeric: 100.00%                                 []
cast …
```
> feat(commands) Add index analyze command

- pkg/cmd/profile/list/list.go
> fix(cmd): profile list using APIKey instead of adminAPIKey

- pkg/cmd/profile/list/list.go
Without annotation the error is not helpful when you have multiple profiles.
Note: this also uses the AdminAPIKey, which might need another change to amend.
> profile/list: show errors in table listing instead of failing

- api/crawler/client.go
- pkg/cmd/crawler/crawl/crawl.go
- pkg/cmd/crawler/crawl/crawl_test.go
- pkg/httpmock/stub.go
The Crawler API does not always provide an error `Message`. IN this case, we show return the error `Code` instead.
> fix(crawler): Correctly display error messages

- Makefile
- pkg/cmd/rules/import/import.go
There was a `rules` missing in the examples for the `algolia rules import` command.
> fix(rules): missing word in example

- pkg/cmd/dictionary/entries/clear/clear.go
Makes the examples for the `algolia dictionary entries clear` command match the actual options.
> fix: examples for dictionary entries clear

- pkg/cmd/indices/delete/delete.go
Virtual replica indices have normal index names, e.g. `replicaName`, but are stored in the index settings as `virtual(replicaName)`. This PR handles deleting virtual replicas with the `algolia index delete` command.
Fixes #166
> fix: handle deleting virtual replicas

- pkg/cmd/indices/config/import/import.go
In the `algolia indices config import` command, these options were not passed correctly to the API client methods 'SaveSynonyms' and 'SaveRules'.
- `--clear-existing-rules`
- `--clear-existing-synonyms` 
- `--forward-synonyms-to-replicas`
Fixes #174
> fix: apply options correctly for indices config import
